app:
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/app
  environment:
    - MONGODB_HOST=rifter_mongodb_1:27017    

mongodb:
  image: tutum/mongodb
  command: mongod --smallfiles
  volumes:
    - ./db/mongodb:/data/db
  ports:
    - "27017"

